#include <rclcpp/rclcpp.hpp>
#include <string>
#include <memory>
#include <iostream>
#include <sys/socket.h>
#include <ctime>
#include <cstring>
#include <netinet/in.h>
#include <arpa/inet.h>
#include "ros_etsi_its_msgs/msg/denm.hpp"
#include <vector>
#include "all_interface_generated.h" // This was generated by `flatc`.
using std::placeholders::_1;

using namespace Gos;
#define PORT 33222 //30100 //33222
#define BUFFER_SIZE 4096

std::string SERVER_ADDR("172.16.2.1"); // Aflonso rsu address

// Function declarations
int sockfd;
void generateMessage(const ros_etsi_its_msgs::msg::DENM::SharedPtr denm_provided); 

void construct_gossip_message(const ros_etsi_its_msgs::msg::DENM::SharedPtr denm_provided); 
::flatbuffers::Offset<Gos::DenmManagementContainer> construct_denm_mgmt_cntnr(flatbuffers::FlatBufferBuilder &builder, const ros_etsi_its_msgs::msg::DENM::SharedPtr denm); 
::flatbuffers::Offset<Gos::DecentralizedEnvironmentalNotificationMessage> construct_denm_payload(flatbuffers::FlatBufferBuilder &builder, const ros_etsi_its_msgs::msg::DENM::SharedPtr denm); 
::flatbuffers::Offset<Gos::SituationContainer> construct_situation_cntnr(flatbuffers::FlatBufferBuilder &builder, const ros_etsi_its_msgs::msg::DENM::SharedPtr denm);
::flatbuffers::Offset<Gos::DENMType> construct_denm_type(flatbuffers::FlatBufferBuilder &builder, const ros_etsi_its_msgs::msg::DENM::SharedPtr denm);


void generateMessage(const ros_etsi_its_msgs::msg::DENM::SharedPtr denm_provided) { 
    std::cout << "generateMessage: Generating DENM message..." << std::endl;
    construct_gossip_message(denm_provided);
    std::cout << "generateMessage: DENM message generation complete." << std::endl;
}

void construct_gossip_message(const ros_etsi_its_msgs::msg::DENM::SharedPtr denm) { 
    struct sockaddr_in server_addr;

    std::cout << "socket_shat----------------------------------" << std::endl;

    // Create a UDP socket
    if ((sockfd = socket(AF_INET, SOCK_DGRAM, 0)) == -1) {
        perror("socket");
        exit(1);
    }

    flatbuffers::FlatBufferBuilder builder;
    std::cout << " ---------------------------------------------------------------------------- " << std::endl;
    std::cout << "Building DENM for station id: " << denm->its_header.station_id << std::endl;
    std::cout << "Building DENM for station id: " << denm->its_header.message_id << std::endl;
    

    // header
    //int32_t trigger_denm = 0;
    ::flatbuffers::Offset<Gos::ItsPduHeader> header = Gos::CreateItsPduHeader(builder, 2, denm->its_header.message_id, denm->its_header.station_id); 
    printf("Is my trigger set properly %u\n", denm->its_header.message_id);
    //::flatbuffers::Offset<Gos::DENMType> denm_type_value = trigger_denm;
    //auto denm_type_value = Gos::DENMType_DENM_REQ_TRIGGER; 
    auto denm_type_value = Gos::DENMType_DENM_REQ_UPDATE;

    // generation time
    //uint64_t gen_del_time = 0; //denm->detection_time; 

    // Create the DENM payload
    //int32_t Gos_DENMType_TYPE_1 = 0;
    auto denm_payload = construct_denm_payload(builder, denm); 
    //Gos_DENMType_enum_t my_denm_type = Gos_DENMType_TYPE_1;
    //auto denm_payload = construct_denm_payload(builder, denm, my_denm_type);

    // Create the DENM message
    struct flatbuffers::Offset<Gos::DENMessage> denm_msg = Gos::CreateDENMessage(builder, header, denm_payload);

    struct flatbuffers::Offset<Gos::DENM> denm_full = Gos::CreateDENM(builder, denm_type_value, denm_msg);


    
    flatbuffers::Offset<void> msgOption = denm_full.Union();
    ::flatbuffers::Offset<FacilityLayerReception> fac_reception_message = CreateFacilityLayerReception(builder, Gos::FacilityLayerMessage_DENM, msgOption); 

    flatbuffers::Offset<void> gossip_option = fac_reception_message.Union();
    ::flatbuffers::Offset<GossipMessage> gossip_msg = CreateGossipMessage(builder, Gos::GossipType::GossipType_FacilityLayerReception, gossip_option);
    builder.Finish(gossip_msg);

    uint8_t* buffer = builder.GetBufferPointer();
    uint64_t size = builder.GetSize();

    // Verify whether the buffer is valid
    flatbuffers::Verifier verifier(buffer, size);
    bool succ = VerifyGossipMessageBuffer(verifier);
    std::cout << "gossip message verified: " << succ << std::endl;
    if (!succ) {
        std::cout << "buffer is invalid" << std::endl;
    } else {
        std::cout << "buffer is valid" << std::endl;
    }
    printf("Total size of the buffer %zu\n", size);

    // Configure server address
    server_addr.sin_family = AF_INET;
    server_addr.sin_port = htons(PORT);
    server_addr.sin_addr.s_addr = inet_addr(SERVER_ADDR.c_str());  // localhost
    if (sendto(sockfd, buffer, size, 0, (struct sockaddr*)&server_addr, sizeof(server_addr)) == -1) {
        perror("sendto");
        exit(1);
    } else {
        printf("DENM Information sent to server\n");
    }
    printf("Message sent to the server!\n");
    close(sockfd);
}


::flatbuffers::Offset<Gos::DecentralizedEnvironmentalNotificationMessage> construct_denm_payload(flatbuffers::FlatBufferBuilder &builder, const ros_etsi_its_msgs::msg::DENM::SharedPtr denm) {
    
    // Construct the DENM management container
    auto denm_mgmt_cntr = construct_denm_mgmt_cntnr(builder, denm);

    //Gos_DENMType_enum_t denm_type
    
    // Construct the situation container (Assuming this is similar to how you construct the other containers)
    auto situation_cntnr = construct_situation_cntnr(builder, denm);
    
    // Construct the location container
    //auto location_cntnr = construct_location_cntnr(builder, denm);
    
    // Construct the alacarte container (if applicable)
    //auto alacarte_cntnr = construct_alacarte_cntnr(builder, denm);
    
    // Create the Decentralized Environmental Notification Message (DENM) payload
    // ::flatbuffers::Offset<Gos::DecentralizedEnvironmentalNotificationMessage> denm_payload = Gos::CreateDecentralizedEnvironmentalNotificationMessage(
    //     builder, 
    //     mgmt_cntnr, 
    //     situation_cntnr, 
    //     location_cntnr, 
    //     alacarte_cntnr
    // );
    ::flatbuffers::Offset<Gos::DecentralizedEnvironmentalNotificationMessage> denm_payload = Gos::CreateDecentralizedEnvironmentalNotificationMessage(
        builder, 
        denm_mgmt_cntr,
        situation_cntnr
    );

    return denm_payload;
}

// Implement other necessary functions similar to how CPM was done but tailored for DENM
::flatbuffers::Offset<DenmManagementContainer> construct_denm_mgmt_cntnr(flatbuffers::FlatBufferBuilder &builder, const ros_etsi_its_msgs::msg::DENM::SharedPtr ptr){

    
    //station type
    uint64_t originating_station_id_new = 1; 
    // Action ID (Assuming `action_id` is a complex type with its own FlatBuffers table)
    ::flatbuffers::Offset<ActionID> action_id = Gos::CreateActionID(builder, 
                                                                    originating_station_id_new,
                                                                    ptr->management.action_id.sequence_number);

    // Detection time
    uint64_t detection_time = ptr->management.detection_time;

    // Reference time
    uint64_t reference_time = ptr->management.reference_time;

    // Termination (Assuming this is an enum type and needs casting)
    Gos::Termination termination = static_cast<Gos::Termination>(ptr->management.termination);

    // Event position
    uint32_t semi_major_confidence = 1;
    uint32_t semi_minor_confidence = 2;
    uint32_t semi_major_orientation = 3;
    ::flatbuffers::Offset<Gos::PositionConfidenceEllipse> pos_conf = Gos::CreatePositionConfidenceEllipse(builder,
                                                                                                        semi_major_confidence,  
                                                                                                        semi_minor_confidence,
                                                                                                        semi_major_orientation);
    int32_t value_new = 0;
    uint32_t confidence_dummy = 1;                                                                                                     

    ::flatbuffers::Offset<Gos::Altitude> altitude = Gos::CreateAltitude(builder, value_new, confidence_dummy);
    int32_t lat= 0;
    int32_t lon = 0;
    ::flatbuffers::Offset<ReferencePosition> event_pos = Gos::CreateReferencePosition(builder, 
                                                                                       lat,
                                                                                       lon,
                                                                                       pos_conf, 
                                                                                       altitude);

    // Relevance distance (Enum)
    uint32_t relevent_dist_dummy = 0;
    Gos::RelevanceDistance relevance_distance = static_cast<Gos::RelevanceDistance>(relevent_dist_dummy);

    // Relevance traffic direction (Enum)
    uint32_t relevent_direct_dummy = 0;
    Gos::RelevanceTrafficDirection relevance_traffic_direction = static_cast<Gos::RelevanceTrafficDirection>(relevent_direct_dummy);

    // Validity duration
    uint32_t validity_duration = ptr->management.validity_duration;

    // Transmission interval
    uint32_t transmission_interval = ptr->management.transmission_interval;

    // Station type
    //Gos::StationType stn_type = static_cast<Gos::StationType>(ptr->management.station_type);
    Gos::StationType stn_type = static_cast<Gos::StationType>(ptr->management.station_type.value);
    //auto uint32_t trigger = 1;
    //::flatbuffers::Offset<StationType> station_type_for_inserting = Gos::EnumNameStationType(builder,trigger);

    // ::flatbuffers::Offset<DenmManagementContainer> denm_mgmt_cntr = Gos::CreateDenmManagementContainer(builder, 
    //                                                                                                     action_id, 
    //                                                                                                     detection_time, 
    //                                                                                                     reference_time, 
    //                                                                                                     termination, 
    //                                                                                                     event_pos, 
    //                                                                                                     relevance_distance, 
    //                                                                                                     relevance_traffic_direction, 
    //                                                                                                     validity_duration, 
    //                                                                                                     transmission_interval, 
    //                                                                                                     stn_type);

    //mgmt_cntr = ::flatbuffers::Offset<DenmManagementContainer> 
    ::flatbuffers::Offset<DenmManagementContainer> denm_mgmt_cntr = Gos::CreateDenmManagementContainer(builder,
                                                                                                        action_id, 
                                                                                                        detection_time, 
                                                                                                        reference_time, 
                                                                                                        termination,
                                                                                                        event_pos,
                                                                                                        relevance_distance,
                                                                                                        relevance_traffic_direction,
                                                                                                        validity_duration,
                                                                                                        transmission_interval,
                                                                                                        stn_type
                                                                                                        );


    return denm_mgmt_cntr;
}

// Function to construct the situation container
::flatbuffers::Offset<Gos::SituationContainer> construct_situation_cntnr(flatbuffers::FlatBufferBuilder &builder, const ros_etsi_its_msgs::msg::DENM::SharedPtr ptr) {

    // Information Quality
    uint32_t information_quality = ptr->situation.information_quality.value;//denm->information_quality.value

    //information_quality;
    // Cast the cause_code to the appropriate type before passing it to Gos::CreateCauseCode
    ::flatbuffers::Offset<Gos::CauseCode> event_type = Gos::CreateCauseCode(
                                                            builder, 
                                                            static_cast<Gos::CauseCodeType>(95), //static_cast<Gos::CauseCodeType>(ptr->situation.event_type.cause_code),  // Cast to Gos::CauseCodeType
                                                            static_cast<Gos::CauseCodeType>(ptr->situation.event_type.sub_cause_code));


    // Event Type
    //::flatbuffers::Offset<Gos::CauseCode> event_type = Gos::CreateCauseCode(builder, 
      //                                                                      ptr->situation.event_type.cause_code, 
                                                                            //ptr->situation.event_type.sub_cause_code);

    //::flatbuffers::Offset<Gos::CauseCode> cause_code_offset = Gos::CreateCauseCode(builder, cause_code, sub_cause_code);
    // Linked Cause (if applicable)
    //::flatbuffers::Offset<Gos::CauseCode> linked_cause = Gos::CreateCauseCode(builder, 
                                                                  //            ptr->situation.linked_cause.cause_code, 
                                                                  //            ptr->situation.linked_cause.sub_cause_code);

    // Event History (if applicable)
    // std::vector<::flatbuffers::Offset<Gos::EventPoint>> event_points;
    // for (const auto& event_point : ptr->situation.event_point) {
    //     // Assuming there's a function to create a DeltaReferencePosition similar to ReferencePosition
    //     auto event_pos = Gos::CreateDeltaReferencePosition(builder, 
    //                                                     event_point.lat, 
    //                                                     event_point.lon, 
    //                                                     /* position confidence */ nullptr, 
    //                                                     /* altitude */ nullptr);
        
    //     // Extracting the delta time and information quality
    //     uint32_t event_delta_time = event_point.timestamp; // Assuming timestamp is appropriate for event_delta_time
    //     uint32_t information_quality = event_point.information_quality.value; // Assuming .value holds the correct type

    //     // Creating the EventPoint object
    //     auto event_point_offset = Gos::CreateEventPoint(builder, event_pos, event_delta_time, information_quality);
    //     event_points.push_back(event_point_offset);
    // }

    // // Create the EventHistory object
    // auto event_history = Gos::CreateEventHistory(builder, builder.CreateVector(event_points));

    // Create the SituationContainer
    // Create a default Offset<Gos::CauseCode> if no valid value is available
    ::flatbuffers::Offset<Gos::CauseCode> linked_cause_code_offset;

// If there's no linked cause code, it will remain as a default empty offset.
    linked_cause_code_offset = flatbuffers::Offset<Gos::CauseCode>();
    ::flatbuffers::Offset<Gos::SituationContainer> situation_cntnr = Gos::CreateSituationContainer(builder, 
                                                                                                    information_quality, 
                                                                                                    event_type,  
                                                                                                    linked_cause_code_offset);

    return situation_cntnr;
}


class DenmSendNode : public rclcpp::Node
{
public:
    DenmSendNode() : Node("denm_send_node")
    {
        // Declare and get the parameter "Trigger"
        this->declare_parameter<int>("trigger", 10);  // Default value is 22
        int trigger_denm;
        this->get_parameter("trigger", trigger_denm);
        RCLCPP_INFO(this->get_logger(), "Trigger Set to: %d", trigger_denm);

        // Construct the server address or use a predefined IP adress
        std::string cohda_addr = "192.168.1" + std::to_string(trigger_denm) + ".108";
        server_addr_ = SERVER_ADDR;//cohda_addr;
        std::cout << "SERVER_ADDR: " << server_addr_ << std::endl;

        // Create the DENM message
        auto denm_ = std::make_shared<ros_etsi_its_msgs::msg::DENM>();

        // Fill the DENM message with necessary data
        uint32_t trigger_kodo = static_cast<uint32_t>(trigger_denm);

        denm_->its_header.station_id = 1;
        denm_->its_header.message_id = trigger_kodo;

        if (trigger_kodo == 10) {

            RCLCPP_INFO(this->get_logger(), "Roadwork trigger is successfully sent.");
            printf("DENM with ROADWORKS Warning Sent CAUSE_CODE=3\n");

        } else if (trigger_kodo == 20) {

            RCLCPP_INFO(this->get_logger(), "AC Accident.");
            printf("DENM with Accident Warning Sent CAUSE_CODE=99\n");

        } else if (trigger_kodo == 30) {

            RCLCPP_INFO(this->get_logger(), "Emergency vehicle approaching.");
            printf("DENM with Emergency Vehicle Approaching Warning Sent CAUSE_CODE=95\n");

        } else {

            RCLCPP_INFO(this->get_logger(), "Unknown trigger parameter: %d", trigger_kodo);
        }

        //Start filling Facility layer maessage 
        generateMessage(denm_);

        // Optionally create a timer for periodic tasks
        timer_ = this->create_wall_timer(
            std::chrono::seconds(1),
            [this]() { this->timer_callback(); });
    }

private:
    void generateMessage(const ros_etsi_its_msgs::msg::DENM::SharedPtr denm) {
        // Populate the DENM message here
        // Example:
        // denm->data_field = some_value;
        std::cout << "generateMessage: Generating DENM message..." << std::endl;
        construct_gossip_message(denm);
        std::cout << "generateMessage: DENM message generation complete." << std::endl;
    }

    void timer_callback() {
        // Do something periodically
        RCLCPP_INFO(this->get_logger(), "Timer callback");
    }

    std::string server_addr_;
    //std::string SERVER_ADDR;
    const ros_etsi_its_msgs::msg::DENM::SharedPtr denm;
    rclcpp::TimerBase::SharedPtr timer_;
};

int main(int argc, char * argv[])
{
    rclcpp::init(argc, argv);
    rclcpp::spin(std::make_shared<DenmSendNode>());
    rclcpp::shutdown();
    return 0;
}


